spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: admin
      password: 12345
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8086